### ISSUE TITLE
[Autorest/M4] Version Bump Checklist

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.csharp#1216]
This is a checklist and playbook of the steps needed to successfully bump autorest / m4 in autorest.csharp (and later azure-sdk-for-net).

# autorest.csharp 
- [ ] Bump autorest (Example)[https://github.com/Azure/autorest.csharp/commit/6182984d59642e47ee12cb6b2bf54d4a9a0386c8]
   - [ ] package.json (autorest)
   - [ ] readme.md (autorest.core)
   - [ ] src/AutoRest.CSharp/readme.md (M4)
- [ ] npm install
- [ ] Regenerate CodeModel
   - [ ] `cd .\src\AutoRest.CodeModel`
   - [ ] `dotnet run`
- [ ] `git commit` the bump files
- [ ] `.\eng\Generate.ps1 -reset`
- [ ] `git commit` any generated/yaml changes
- [ ] `dotnet test`
- [ ] Kick off bump PR in autorest.csharp
- [ ] `dotnet pack`
- [ ] Copy nuget to local feed

# azure-sdk-for-net

**Comment by AlexanderSher** [comment]
Need to convert that into *.md file
