### ISSUE TITLE
v3: Overview

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/autorest.csharp#211]
# Building the code generator
- [x] Build on top AutoRest runtime v3 
- [ ] Add csharp autorest configuration model (#7813)
- [x] Add support for autorest code model (#7811)
- [x] Add support for swagger extensions (#7812)
- [ ] Add csharp specific transformations (#7814)
- [x] Add csharp code generation plugin (#7815)
- [x] Validate generate csharp code against test server (#7816)
- [ ] Hook up auto-PR support for generated code (#7819)

# Designing the generated code
- [x] Design the exact set of csharp code to generate (#7817)
- [ ] Design shared multi-api support for generated code (#7818)

# Plan of action
- Replace existing storage code generator
  - This will not encompass the final design. It is simply to get the pieces together, find issues, and allow the current generator for Storage to be replaced. Think of this as a prototype.
- Track 2 data plane (Storage, KeyVault, AzConfig, some CogServices)
  - This involves a strong set of design requirements. Other services outside of this set will be tested for unknown issues. This is still primarily focused on data plane, but management plane would at least be acknowledged when designing.
  - May or may not involve generating public surface APIs. It depends on timelines and how the team wants to proceed. If not, it would at least have a 'finalized' protocol layer.
  - Would need to have multi-api/Azure profile integrated into the design at this point.
- Replace management plane code generator
  - This is a long term goal. It involves other teams involvement (those that now maintain the management plane SDKs). It would be a breaking change for all of their SDKs.
  - There are conventions that are used by management plane that would need to be designed and handled appropriately in the generator.

**Comment by MiYanni** [comment]
We have separate issues for remaining action items. Closing this umbrella issue.
