### ISSUE TITLE
Remove ErrorResponse<T> from Generator.Shared

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2148]
### Summary

[ErrorResponse\<T\>](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/ErrorResponse.cs) is not returned by any DPG APIs.  Per https://github.com/azure/azure-sdk-for-net/issues/27852, we would like to move to using `NullableResponse<T>` instead.  `ErrorResponse<T>` should be removed.

### Tasks involved

- [ ] `ErrorResponse<T>` is removed from Generator.Shared
- [ ] [`ProcessHeadAsBoolMessage`](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/HttpPipelineExtensions.cs#L56) is updated to return `NullableResponse<T>`
- [ ] Generator is updated if changes need to be made when `head-as-boolean: true`.

**Comment by annelo-msft** [comment]
Blocked by https://github.com/azure/azure-sdk-for-net/issues/27852

**Comment by annelo-msft** [comment]
Let's start by removing ErrorResponse\<T\> and ignoring the tests that fail.
