### ISSUE TITLE
Add a document for describing flags to generate DPG and HLC

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#2188]
Previously our default SDK was HLC and now our default SDK is DPG. Some customers are getting confused about why the SDK has stopped generating models. I think it would be super helpful if we provide a document describing flags to generate DPG and HLC including the default behaviour. 

- [ ] DPG - Add flag to generate DPG library with the description of how the generated code would look like.
- [ ] HLC - Add `generation1-convenience-client` flag with the description of how the generated code would look like.
- [ ] Add description about when to use the HLC generator vs. the DPG generator.

**Comment by ShivangiReja** [comment]
We have some customer issues regarding this - 
- https://github.com/Azure/autorest.csharp/issues/2182
- https://github.com/Azure/autorest.csharp/issues/198#issuecomment-1116414663

**Comment by ttrunck** [comment]
Is it possible to combine the `generation1-convenience-client` with the `add-credential` flag? It seems that `add-credential` is ignored when I pass both.
How could I have both credential support and model generation?
