### ISSUE TITLE
Implement new RefDocs Requirements

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2239]
## Summary

DPG client protocol methods don't take or return [model types](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-model-types), and this has a negative impact on customer UX.  We will provide good documentation to mitigate this concern and help customer succeed using protocol methods.  The reference documents for each protocol method will include:

- Links to the REST API docs describing the operation and expected payloads
- Copy-and-paste sample code for mainline scenario methods

## Existing Reference Docs

An example of the documentation currently generated for a protocol operation can be found here: https://github.com/Azure/azure-sdk-for-net/blob/783c75c69eaac8b05de1bd0ccb7f3e87bfddf90b/sdk/purview/Azure.Analytics.Purview.Scanning/src/Generated/PurviewScanClient.cs#L291

It contains XML tags for:
- `<param></param>` for each input parameter 
- `<exception></exception>` for each exception thrown
- `<remarks></remarks>` containing the following:
    - `<code></code>` for the Request Body schema
    - `<code></code>` for the Response Body schema
    - `<code></code>` for the Error Response
    
We would like to change it in the following ways.

## Updates to Reference Docs

- [ ] Change the `<param name="content">`  tag:

    From: `<param name="content"> The content to send as the body of the request. </param>`
    To: `<param name="content"> The content to send as the body of the request. Details of the request body schema are in the Remarks section below.</param>`

- [ ] Change the `<param name="context">` tag:
    From: `<param name="context"> The request context, which can override default behaviors on the request on a per-call basis. </param>`
    To: `<param name="context"> The request context, which can override default behaviors of the client pipeline on a per-call basis. </param>`

- [ ] Add a `<returns>` tag describing the method's return value.  If the return value is `Response` or `Task<Response>`, the text should be as follows:

    `The response returned from the service. Details of the request body schema are in the Remarks section below.`

- [ ] Add an `<exception>` tag:

    `<exception cref="RequestFailedException">Service returned a non-success status code.</exception>`

### Examples

- [ ] Add an example section before remarks section using `<example>` tag with a copy-and-paste sample showing two samples that illustrate:

    - Create client
    - Create `RequestContent` using C# anonymous types and `RequestContent.Create` method.  Use `<outer>-<inner>-<propertyName>` to populate string parameter values.
    - Calling the method
    - Parse the `Response` returned from the method using `JsonDocument.Parse` 
    - Print the values from the response body using `Console.WriteLine`

####

  1. The first sample will show the method call passing only required properties for the input request body
  2. The second sample will show the method call passing all properties for the input request body
  3. Consider adding example code in a separate file and pull it into the docs from there to ensure it builds

Refer [sample Example section](https://review.docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview&branch=ShivangiTestBranchWithoutFiles#examples) for more details.

### Remarks

We will update the `<remarks></remarks>` tag as follows:

- [ ] Remove `<remarks><code></code></remarks>` block for Error Response.

- [ ] Add link to REST API documents for the given operation.  This will be obtained as follows:
    1. If https://swagger.io/specification/v2/#externalDocumentationObject contains a URI, use this for the link
    2. Use the [Formula to create the REST API link](https://github.com/Azure/autorest.csharp/issues/2253) provided by @mikekistler.

- [ ] Update `<remarks><code></code></remarks>` for the Request Body schema to indicate whether the parameter is required or optional.
- [ ] Update `<remarks><code></code></remarks>` for the Request Body schema with the parameter descriptions.
- [ ] Update `<remarks><code></code></remarks>` for the Response Body schema with the parameter descriptions.
- [ ] Add Polymorphic types
   - [ ]  If a method takes one for the derived type, add description - `This method takes one of the  JSON object below as a payload. Please select a JSON object to view the schema`
   - [ ] The list of polymorphic definitions is potentially long. So we decided providing several levels of expanding menu.
        - One for the list of all derived definitions (Show a few with a "See More..." link that expands to the full list
        - When one of the definition names is clicked, the page expands to show the schema for that particular JSON object in place.

Refer [sample `Remarks` section](https://review.docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview&branch=ShivangiTestBranchWithoutFiles#remarks) to see the polymorphic types.

 v1.1 requirement development tracked by per https://github.com/Azure/azure-sdk-for-net/issues/28962#issue-1247187851

## References
- DPG design meeting recording from 05/02/2022: [First Section](https://microsoft-my.sharepoint.com/:v:/p/annelo/EcDYRcj5Lf9FnkFBN_2Rs10B7kKbdhmVNDNc_zPBZYO7IA?e=ZPEpDS), [Second Section](https://microsoft-my.sharepoint.com/:v:/p/annelo/EUnAgGsKKTJIhEmarXnp29cBQVRebILj9KNn5t-1cyA4lA?e=v0HtcB) [MS INTERNAL ONLY] 
- https://gist.github.com/ShivangiReja/c9146016b4812f7c0f475eec28e9c131
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments

#### Was: 
Implement the new RefDocs requirements described by the work done for https://github.com/Azure/azure-sdk-for-net/issues/28833.

**Comment by archerzz** [comment]
I split this task into 3 sub-tasks:

- https://github.com/Azure/autorest.csharp/issues/2285
- https://github.com/Azure/autorest.csharp/issues/2286
- https://github.com/Azure/autorest.csharp/issues/2288

**Comment by lirenhe** [comment]
We completed all requirement work for DPG 1.0.
Update the label and move it to the next milestone.

**Comment by archerzz** [comment]
closing since all sub-tasks are finished.
