### ISSUE TITLE
Generate .NET client from language/textanalytics Cadl API description

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2331]
For our August MVP, we will generate a .NET client for a service that will be specified mid-July.  This issue tracks the work to validate that the DPG generator can generate the client and its protocol methods, to achieve parity with what DPG v1.0 can do from swagger files.

Per @lmazuel's suggestion, we will use https://github.com/Azure/cadl-azure/tree/main/packages/cadl-samples/data-plane/language/textanalytics as one of the input files to validate parity with DPG v1.0.

### Design for Cadl prototype

We will generate a .NET SDK directly from the Cadl files found at: https://github.com/Azure/cadl-azure/tree/main/packages/cadl-samples/data-plane/language/textanalytics

**Note:** The TextAnalytics swagger file describes a long running operation and in a final GA TextAnalytics library, AnalyzeText would be represented as an LRO.  For the purposes of porting the DPG generator to Cadl, we will treat each operation as a basic REST operation and generate it as a simple service operation on the TextAnalytics DPG client.

#### Cadl features to support in DPG generation

- [ ] `@server` tag generates URI endpoint parameter to client constructor
- [ ] Client is generated in namespace `Azure.Language.TextAnalytics`
- [ ] `AnalyzeClientOptions.ServiceVersion` enum contains version `V2022-05-15-Preview = 1`
- [ ] Name of client is `AnalyzeClient`
- [ ] public `AnalyzeText` and `AnalyzeTextAsync` methods are generated with signature `public virtual Response AnalyzeText(RequestContent content, bool? showStats = null, RequestContext context = null)`
- [ ] Input model is not shown in protocol method signature, instead `RequestContent` parameter is passed
- [ ] Optional parameter
- [ ] `bool` parameter
- [ ] Output model is not represented in protocol method return type, instead method returns `Response`
- [ ] `@doc` decorator content is printed to `<summary>` tag in doc comments
- [ ] internal `CreateAnalyzeTextRequest` method is generated 
- [ ] `pipeline.CreateMessage` is called with `ResponseClassifier200`
- [ ] Request method is POST
- [ ] Path is `/language/:analyze-text`
- [ ] `api-version` query parameter is appended
- [ ] `showStats` query parameter is appended if provided
- [ ] `Accept` header is `application/json`
- [ ] `Content-Type` header is `application/json`

#### Expected output

Expected output for the prototype DPG client described in https://github.com/Azure/azure-sdk-for-net/pull/29555

This PR contains a simple client generated inside the sdk/template project.  The autorest.md file has been updated to indicate how credentials should be generated in the constructor.

**Comment by annelo-msft** [comment]
@lirenhe, FYI.  This provides a description of the expected output of the DPG generator on the language/textanalytics file.

**Comment by annelo-msft** [comment]
Removing this as a validation target for mid-July milestone.  @jsquire FYI

**Comment by lirenhe** [comment]
@archerzz , could you help to verify the generated code to make sure LRO, Paging etc are expected?  thanks

**Comment by archerzz** [comment]
The latest CADL files are in this PR: https://github.com/Azure/azure-rest-api-specs/pull/21010
However, right now the CADL files do not compile due to various errors.

**Comment by lirenhe** [comment]
Close it as completed
