### ISSUE TITLE
Generate round-trip polymorphic models from Cadl with extends and discriminator keywords

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2361]
### Round trip polymorphic models

This issue tracks the work to implement generation of round-trip models:
- That use inheritance via the Cadl `extends` keyword
- That use [polymorphism with discriminators](https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#polymorphism-with-discriminators) via the Cadl `@discriminator` decorator
- That have properties that are polymorphic types

#### Input Cadl file
[Cadl testserver models/inheritance](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/inheritance)

#### Expected output

Basic inheritance using `extends` keyword:
- [ ] [DerivedFromBaseClassA.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-polymorphic-basic/sdk/template/Azure.Template/src/Generated/Models/DerivedFromBaseClassA.cs)
- [ ] [DerivedFromBaseClassA.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-polymorphic-basic/sdk/template/Azure.Template/src/Generated/Models/DerivedFromBaseClassA.Serialization.cs)
- [ ] Type derives from BaseClass
- [ ] Constructor calls BaseClass constructor to initialize baseClassProperty
- [ ] Constructor only initializes DerivedClassAProperty
- [ ] Serialization Write method writes both BaseClassProperty and DerivedClassAProperty
- [ ] Serialization DeserializeDerivedFromBaseClassA method reads both baseClassProperty and derivedClassAProperty

Polymorphism with discriminators:
- [ ] [BaseClassWithDiscriminator.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-polymorphic-basic/sdk/template/Azure.Template/src/Generated/Models/BaseClassWithDiscriminator.cs)
- [ ] [BaseClassWithDiscriminator.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-polymorphic-basic/sdk/template/Azure.Template/src/Generated/Models/BaseClassWithDiscriminator.Serialization.cs)
- [ ] Discriminator is not set in initialization constructor
- [ ] Discriminator is set in serialization constructor
- [ ] DiscriminatorProperty is an internal property
- [ ] Serialization DeserializeBaseClassWithDiscriminator reads discriminator and instantiates and returns appropriate base type
- [ ] If no discriminator is found, the deserialization constructor is called with discriminatorProperty initialized to default.
- [ ] [DerivedFromBaseClassWithDiscriminatorA.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-polymorphic-basic/sdk/template/Azure.Template/src/Generated/Models/DerivedFromBaseClassWithDiscriminatorA.cs)
- [ ] [DerivedFromBaseClassWithDiscriminatorA.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-polymorphic-basic/sdk/template/Azure.Template/src/Generated/Models/DerivedFromBaseClassWithDiscriminatorA.Serialization.cs)
- [ ] Type derives from BaseClassWithDiscriminator
- [ ] Constructor calls BaseClassWithDiscriminator constructor to initialize baseClassProperty
- [ ] Initialization constructor sets DiscriminatorProperty to "A"
- [ ] Serialization constructor sets DiscriminatorProperty from deserialized value or "A"

Model with polymorphic property:
- [ ] [ModelWithPolymorphicProperty.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-polymorphic-basic/sdk/template/Azure.Template/src/Generated/Models/ModelWithPolymorphicProperty.cs)
- [ ] [ModelWithPolymorphicProperty.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-polymorphic-basic/sdk/template/Azure.Template/src/Generated/Models/ModelWithPolymorphicProperty.Serialization.cs)

#### Test coverage
Tests should be added to the cadl-ranch test server to validate that values with discriminators are deserialized to the correct type, BaseTypeWithDiscriminator initializes the discriminator property to default and that polymorphic property can have values of derived types.

**Comment by annelo-msft** [comment]
Per @bterlson, align with https://github.com/microsoft/cadl/issues/335

**Comment by annelo-msft** [comment]
Per @KrzysztofCwalina, it is acceptable for DPG 2.0 to generate the same output as the HLC generator.  @AlexanderSher FYI.
As such, I am removing the `needs-design` label.

**Comment by lirenhe** [comment]
@AlexanderSher, do we have the InputModel defined for polymorphic models?

**Comment by chunyu3** [comment]
same as https://github.com/Azure/autorest.csharp/issues/2484

**Comment by lirenhe** [comment]
close it as resolved
