### ISSUE TITLE
Close outstanding .NET DPG Model design questions

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2468]
### Context

This issue tracks outstanding model design questions that aren't tracked in other GH issues in the [.NET DPG - Model Generation](https://github.com/orgs/Azure/projects/216) project.

#### Questions

- [x] Should models use `#nullable disable`?  **Yes, see" https://github.com/Azure/azure-sdk-for-net/pull/30176#discussion_r932540015
- [x] Should strings passed to a model constructor be checked for both null and empty?:  check MPG and HLC implementation first  
  - For MPG, we don't check empty, see [here](https://github.com/Azure/autorest.csharp/blob/849394266e905156b708523eb1115630f0c30c6f/samples/Azure.Management.Storage/Generated/Models/Action.cs#L22).
  - #2856 
- [x] <del>If a `@doc` decorator provides a description of a property, should the C# doc comment for a getter say "Gets the \<`@doc` value\>" or just output the doc value?</del>
- [x] What is the mapping from Cadl built-in types to C# types? **See**: https://github.com/Azure/azure-sdk-for-net/blob/main/doc/design/GeneratedClientDesign.md#type-mappings-from-cadl-to-net
- [x] Do Cadl built-in types let us represent everything we need in Azure and if so, how?: yes
- [x] How does `@format` work? It's not recommended to use in CADL, since we have `uri`, `plainDate`... which previously is `string` with `format=uri`.
- [x] Do we need to do anything special to use the `@key` Cadl decorator? **No, see**: https://github.com/Azure/autorest.csharp/issues/2488
- [x] How do we handle `@secret`? : postponed
- [x] Do we handle all the [built-in decorators](https://microsoft.github.io/cadl/standard-library/built-in-decorators)? : NO
- [x] Should generated models always go in a `.Models` namespace? We have parameter "model-namespace". `true` means the generated models will have a `.Models` namespace, otherwise models will have the same namespace as client.
- [x] Should enums go in the `.Models` namespace? **Enums should go in the same namespace as models, see:** https://github.com/Azure/azure-sdk-for-net/blob/main/doc/design/GeneratedClientDesign.md#enums
- [x] Can we represent all shapes of client/subclient hierarchy?
- [x] Should round-trip model properties have setters?  **Yes, see** https://github.com/Azure/azure-sdk-for-net/pull/11687#discussion_r418249627
- [x] How will we map built-in cadl-azure types (e.g. cadl-azure-core) to .NET Core/other types? https://github.com/Azure/autorest.csharp/issues/2450

**Comment by annelo-msft** [comment]
Working model taxonomy:
  (Or, model considerations/test cases)

- Property of model
    - input/output/round-trip
- Property of model property
    - primitive/collection/dictionary/model type
    - value type/reference type
    - required/optional
    - nullable/non-nullable
-

**Comment by lirenhe** [comment]
@archerzz, could you follow up on the remaining items?  Thanks
