### ISSUE TITLE
Support multiple content types in DPG + CADL  (Convinience API)

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2553]
- [ ] Add `InputOperationBody` type that would represent one of the body types
- [ ] Add `IReadOnlyList<InputOperationBody> Bodies` to `InputOperation`
- [ ] Change `RestClientBuilder.CreateRequestMethodBuildContext` to use `Bodies` instead of search for parameter
- [ ] Modify [loadOperation](https://github.com/Azure/autorest.csharp/blob/205fd904ade97db3966955124dcc88e4e216923b/src/CADL.Extension/Emitter.Csharp/src/emitter.ts#L237) in CADL emitter to create `InputOperationBody` instead of adding body parameter.
- [ ] Update `CodeModelConverter`

**Comment by lirenhe** [comment]
@annelo-msft   @AlexanderSher,  is this item within the scope of August MVP?

**Comment by AlexanderSher** [comment]
I think not. We don't have complex bodies in Metrics Advisor.

**Comment by annelo-msft** [comment]
@AlexanderSher, can you help me understand the context for this issue?  What is the Cadl input and what is the expected output?  Or does this refer to generator internals only?

**Comment by lirenhe** [comment]
As discussed, we need to complete this item by beta2. 
@chunyu3  @AlexanderSher， could you work together on the Emitter and codeGen part?  thanks

**Comment by chunyu3** [comment]
depend on design https://github.com/Azure/autorest.csharp/issues/2619

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/3056. close this one.
