### ISSUE TITLE
DPG v2.0b2: Show Parity with DPG v1.0

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2578]
One of the requirements for the [August MVP Arch Board](https://github.com/Azure/azure-sdk/issues/4549) is to show parity with DPG v1.0.  This means that we can generate the same client from a Cadl file in the August MVP that we could generate from an OpenAPI file in DPG v1.0.

This should include the following generation features:

DPG **v2.0b1**:
- [x] Main namespace and assembly name **from config**
- [x] Client generation
- [x] Client constructor generation
    - [x] Generation of authentication support for
        - [x] KeyCredential
        - [x] TokenCredential
    - [x] ClientOptions generation
- [x] Subclient generation, **from .NET attributes**
- [x] Protocol methods for basic synchronous REST calls
    - [x] Documentation is generated for the request/response payloads
    - [x] Methods return Response
        - [x] Response.Content contains serialized model
    - [x] Methods support input parameters
        - [x] Primitive types -> primitive types
        - [x] Model types -> RequestContent
        - [x] Extensible enums -> strings
        - [x] Optional value types are made nullable with `?`

**August MVP Deliverable**: We should be able to generate this[ Confidential Ledger APIView](https://apiview.dev/Assemblies/Review/e25a373b908f49ab9a28436af7aede59) from a Cadl description and metadata file.

DPG **v2.0b2**:
- [x] Paging operations
- [x] Long-running operations
- [ ] Multiple content types   Tracked in: https://github.com/Azure/autorest.csharp/issues/3056
- [ ] MatchConditions: via header parameters:  Tracked in https://github.com/Azure/autorest.csharp/issues/3065
- [x] Subclient generation **from Cadl**
- [x] Main namespace and assembly name **from Cadl**

Much of this is covered by:
- https://github.com/Azure/autorest.csharp/issues/2402
- https://github.com/Azure/autorest.csharp/issues/2550

**Comment by lirenhe** [comment]
@annelo-msft , do we need to support header/query parameter & header response as the goal for v2.0b1?

**Comment by annelo-msft** [comment]
@lirenhe, we can support header parameters in request/response for beta2.  I would keep query parameters in beta1 because I believe those show up in DPG1.0 service APIs.

**Comment by annelo-msft** [comment]
@srnagar will propose a unified outline across languages that aligns with this.

**Comment by AlexanderSher** [comment]
With useAuth supported, I think we have parity. @annelo-msft , is this the cadl input we need to use for Confidential Ledger validation: https://github.com/Azure/cadl-azure/blob/main/packages/cadl-samples/data-plane/confidentialledger/confidentialledger.cadl

**Comment by annelo-msft** [comment]
That, as well as the resiliency test cases Laurent created in the cadl-ranch repo.

**Comment by lirenhe** [comment]
Update the title and we will revisit the items in 2.0beta2

**Comment by lirenhe** [comment]
Close this item as we have new issues to track the remaining work.
