### ISSUE TITLE
Typespec Emitter: Improve test coverage for Emitter

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2612]
In current codebase, when execute:  'npm run test', it will report 'Error: No test files found'.
Please create the test project and enable unit test & integration test in this project.

- [x] Generate the test project for unit test & integration test.
- [ ] Create unit test/integration test with test coverage > 85%
- [x] Test execution should be included in CI pipeline.

**Comment by lirenhe** [comment]
You could reference how JS adding unit test. https://github.com/Azure/autorest.typescript/tree/main/packages/autorest.typescript/test/unit

**Comment by chunyu3** [comment]
close this. Because we will use the MGC emitter and will add emitter UT there.
