### ISSUE TITLE
Support Paging from CADL

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2715]
Support Paging:
- [x] emit paging schema
- [x] generate paging protocol method
- [x] generate paging convenience method

**Comment by lirenhe** [comment]
@chunyu3, could you update this item about what part is implemented?  Thanks
