### ISSUE TITLE
Migrate dotnet DPG test cases into CADL-Ranch

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#3439]
Currently, there are a couple of typespec files merged into dotnet repo for test usage.
Those test cases should be moved to CADL-Ranch so that we could have a central places for all the e2e tests.

**MockAPI**

```[tasklist]
### Tasks
- [x] LRO-Basic
- [x] FirstTest
- [x] PetStore
- [x] Models: https://github.com/Azure/autorest.csharp/issues/4845
- [x] Spread: https://github.com/Azure/autorest.csharp/issues/4846
- [ ] https://github.com/Azure/autorest.csharp/issues/4865
```

**TestProjects**

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4847
- [x] https://github.com/Azure/autorest.csharp/issues/4848 Review owner: @ArcturusZhang
- [x] https://github.com/Azure/autorest.csharp/issues/4849 Review owner: @pshao25
- [x] https://github.com/Azure/autorest.csharp/issues/4850 Review owner: @archerzz
- [ ] https://github.com/Azure/autorest.csharp/issues/4851
- [x] https://github.com/Azure/autorest.csharp/issues/4852 Review owner: @chunyu3
- [x] https://github.com/Azure/autorest.csharp/issues/4853 Review owner: @archerzz
- [ ] https://github.com/Azure/autorest.csharp/issues/4854
- [x] https://github.com/Azure/autorest.csharp/issues/4855 Review owner: @live1206
- [x] https://github.com/Azure/autorest.csharp/issues/4856 Review owner: @archerzz
- [x] RenameGetList-TypeSpec: Add local test to verify generated method name. @melina5656
```

**Comment by chunyu3** [comment]
similar as https://github.com/Azure/autorest.csharp/issues/3437
