### ISSUE TITLE
refactor(generator): remove `// <auto-generated/>`

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#3485]
## Description

To improve the output quality of generator, we should try to remove `// <auto-generated/>` in the generated codes.

- [ ] ~remove `// <auto-generated/>` in the writer~
- [x] review errors in the draft PR on `azure-sdk-for-net` repo
- [x] fix as many errors as possible in the generator
- [x] for already published SDKs, if fixing the errors will cause breaking changes, then we should consider either suppress the error or use customization codes to work around
- [x] report errors in analyzer, if there is any
```[tasklist]
### Tasks
```

**Comment by ArcturusZhang** [comment]
Does this also apply to DPG?

**Comment by archerzz** [comment]
We've decided to keep the `// <auto-generated/>` comments, but leverage removing it to find and fix any errors found by analyzers. Then we will modify the analyzers to check generated codes for track2.
