### ISSUE TITLE
[Microsoft Generator CSharp] Create Generator Executable

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#3900]
Create the generator program executable. The executable should provide at a minimum, should support the following:
  - Support providing plugin and plugin version via input.
  - Local plugin lookup and support for automatically downloading plugin via Nuget.
  - Handle concurrent plugin installs from different processes.
  - standard command line arguments
    - `--help`
    - command line parsing fall back to --help on error

In addition, the following command flows should be supported:

- dev on local machine
- ci generating all
- tsp first
- autorest first
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4000
- [ ] https://github.com/Azure/autorest.csharp/issues/4001
- [ ] https://github.com/Azure/autorest.csharp/issues/4093
- [ ] https://github.com/Azure/autorest.csharp/issues/4152
```
