### ISSUE TITLE
[Microsoft Generator CSharp] Create Client Model Plugin

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#3903]
Create the base ClientModel plugin for the generator. The base implementation should be copied from the autorest.csharp generator and should be stripped of any branding. The ClientModel plugin should do the following:
- contain ClientModel specific expressions
- contain ClientModel specific statements
- contain ClientModel specific method bodies
- contain an implementation of the TypeFactory
- contain an implementation of the CodeWriter
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4164
- [ ] https://github.com/Azure/autorest.csharp/issues/4165
- [ ] https://github.com/Azure/autorest.csharp/issues/4166
- [ ] https://github.com/Azure/autorest.csharp/issues/4167
- [ ] https://github.com/Azure/autorest.csharp/issues/4228
```
