### ISSUE TITLE
[TCGC] Adopt `getAllOperation`

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#3994]
Per https://github.com/Azure/typespec-azure/issues/2745
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/typespec-azure/issues/948
- [ ] https://github.com/Azure/autorest.csharp/issues/4747
- [ ] https://github.com/Azure/typespec-azure/issues/951
- [ ] https://github.com/Azure/typespec-azure/issues/969
- [ ] https://github.com/Azure/typespec-azure/issues/980
- [ ] https://github.com/Azure/typespec-azure/issues/981
- [ ] https://github.com/Azure/typespec-azure/issues/988
- [ ] https://github.com/microsoft/typespec/issues/3568
- [ ] https://github.com/Azure/typespec-azure/issues/989
- [ ] https://github.com/Azure/typespec-azure/issues/992
- [ ] https://github.com/Azure/typespec-azure/issues/1007
- [ ] https://github.com/Azure/cadl-ranch/issues/597
- [ ] https://github.com/Azure/typespec-azure/issues/1030
- [ ] https://github.com/Azure/typespec-azure/issues/1046
- [ ] https://github.com/Azure/typespec-azure/issues/1060
- [ ] https://github.com/Azure/autorest.csharp/pull/4841
- [ ] https://github.com/Azure/typespec-azure/issues/1084
- [ ] https://github.com/Azure/typespec-azure/issues/1089
- [ ] https://github.com/Azure/typespec-azure/issues/1091
- [ ] https://github.com/Azure/typespec-azure/issues/1097
- [ ] https://github.com/Azure/typespec-azure/issues/1150
- [ ] https://github.com/Azure/typespec-azure/issues/1212
- [ ] https://github.com/Azure/typespec-azure/issues/1249
```
