### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Output Classes

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4198]
The [Output classes](https://github.com/Azure/autorest.csharp/tree/feature/v3/src/AutoRest.CSharp/Common/Output) should be migrated to the new generator. Any references to brands should be removed as part of the migration, and access modifiers for these classes should be adjusted if necessary.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4473
- [ ] https://github.com/Azure/autorest.csharp/issues/4474
- [ ] https://github.com/Azure/autorest.csharp/issues/4475
- [ ] https://github.com/Azure/autorest.csharp/issues/4476
```
