### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Generation Classes

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4199]
The [Generation classes](https://github.com/Azure/autorest.csharp/tree/feature/v3/src/AutoRest.CSharp/Common/Generation) should be migrated to the new generator. Any references to brands should be removed as part of the migration, and access modifiers for these classes should be adjusted if necessary.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4341
- [ ] https://github.com/Azure/autorest.csharp/issues/4342
- [ ] https://github.com/Azure/autorest.csharp/issues/4343
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/46045
- [ ] https://github.com/Azure/autorest.csharp/issues/4345
- [ ] https://github.com/Azure/autorest.csharp/issues/4346
- [ ] https://github.com/Azure/autorest.csharp/issues/4347
- [ ] https://github.com/Azure/autorest.csharp/issues/4348
- [ ] https://github.com/Azure/autorest.csharp/issues/4349
- [ ] https://github.com/Azure/autorest.csharp/issues/4350
- [ ] https://github.com/Azure/autorest.csharp/issues/4351
- [ ] https://github.com/Azure/autorest.csharp/issues/4352
```

**Comment by m-nash** [comment]
Break this down into smaller chunks.
