### ISSUE TITLE
[Documentation]:  Improve docs for dataplane code generation for more supported features 

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#4213]
Please describe the issue or feature request.

Current site https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/00howtogen lack some detailed information on how the generated SDK would look like for various TypeSpec input.

**Describe your ideas for solutions**
We need to improve the DPG documentation to ensure all our partners would understand the expected SDK would look like for their TypeSpec inputs.

```[tasklist]
### Tasks
- [ ] Multipart/form-data
- [ ] The spread of alias & models
- [ ] Etag headers
- [ ] Long running operations.
- [ ] Discriminator
```
