### ISSUE TITLE
Get the generator changes at par with the System.ClientModel

### ISSUE THREAD

**Issue by pallavit** [Azure/autorest.csharp#4242]
We need to update the latest System.ClientModel-1.1.0-alpha.20240220.1.

This is in preparation for 1.1.0 GA.

In order to do this we need to update the class renames as well as solve for the shared source that no longer exists.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4246
- [ ] https://github.com/Azure/autorest.csharp/issues/4247
- [ ] https://github.com/Azure/autorest.csharp/issues/4248
- [ ] https://github.com/Azure/autorest.csharp/issues/4249
- [ ] https://github.com/Azure/autorest.csharp/issues/4250
- [ ] https://github.com/Azure/autorest.csharp/issues/4245
- [ ] https://github.com/Azure/autorest.csharp/issues/4391
- [ ] https://github.com/Azure/autorest.csharp/issues/4431
- [ ] https://github.com/Azure/autorest.csharp/issues/4445
```
For each of these tasks we want to follow the same strategy for branded or unbranded.  So if we inline a helper method we should do so for all cases.
