### ISSUE TITLE
Remove generator dependency on ClientUtilities

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#4245]
Instead of using Argument in branded libraries and ClientUtilities in unbranded we will simply inline the assert/throw for null and empty.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4316
- [ ] https://github.com/Azure/autorest.csharp/issues/4317
- [ ] https://github.com/Azure/autorest.csharp/issues/4325
- [ ] https://github.com/Azure/autorest.csharp/issues/4326
```

**Comment by m-nash** [comment]
Remove argument from shared source download

**Comment by m-nash** [comment]
Need to emit a helper here to ensure consistency in error messages
