### ISSUE TITLE
Remove generator dependency on ModelSerializationExtensions

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#4246]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4301
- [ ] https://github.com/Azure/autorest.csharp/issues/4274
- [ ] https://github.com/Azure/autorest.csharp/issues/4372
- [ ] https://github.com/Azure/autorest.csharp/issues/4409
- [ ] https://github.com/Azure/autorest.csharp/issues/4413
```
