### ISSUE TITLE
Remove generator dependency on OptionalProperty

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#4250]
Our strategy for Optional static methods will be to inline the checks directly into the code for both branded and unbranded so we are consistent and no longer required the shared source file.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4260
- [ ] https://github.com/Azure/autorest.csharp/issues/4261
- [ ] https://github.com/Azure/autorest.csharp/issues/4262
- [ ] https://github.com/Azure/autorest.csharp/issues/4263
- [ ] https://github.com/Azure/autorest.csharp/issues/4264
- [ ] https://github.com/Azure/autorest.csharp/issues/4269
- [ ] https://github.com/Azure/autorest.csharp/issues/4318
- [ ] https://github.com/Azure/autorest.csharp/issues/4319
```

**Comment by m-nash** [comment]
Need to remove Optional from downloadshared source

**Comment by m-nash** [comment]
Going to keep the helpers and drop the struct to maintain consistency
