### ISSUE TITLE
[Epic] Adopt SdkLibrary from TCGC

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#4299]
Tracking full adoption of using the new SdkLibrary in TCGC and replacing the current code in @azure-tools/typespec-csharp.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4300
- [ ] Adopt getAllClients
- [ ] https://github.com/Azure/autorest.csharp/issues/4534
- [ ] https://github.com/Azure/autorest.csharp/issues/3994
```
