### ISSUE TITLE
Adopt getAllModels

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#4300]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/typespec-azure/issues/300  **block all alias models cases**
- [ ] https://github.com/Azure/typespec-azure/issues/69
- [ ] https://github.com/Azure/typespec-azure/issues/128 **block cases where enum value is used in decorator**
- [ ] https://github.com/Azure/typespec-azure/issues/201
- [ ] https://github.com/Azure/typespec-azure/issues/204
- [ ] https://github.com/Azure/typespec-azure/issues/346 **block LRO**
- [ ] https://github.com/Azure/autorest.csharp/issues/4539
- [ ] https://github.com/Azure/typespec-azure/issues/676
- [ ] https://github.com/microsoft/typespec/issues/3184
- [ ] https://github.com/Azure/typespec-azure/issues/723
- [ ] https://github.com/Azure/typespec-azure/issues/553
- [ ] https://github.com/Azure/typespec-azure/issues/730
```
