### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Writers: Writer Helpers

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4347]
The writer helper classes should be migrated and stripped of any branding.

Classes to migrate:
- [FormattableStringHelpers](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/FormattableStringHelpers.cs)
- [RequestWriterHelpers](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/RequestWriterHelpers.cs)
- [ResponseWriterHelpers](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/ResponseWriterHelpers.cs)
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4560
- [ ] https://github.com/Azure/autorest.csharp/issues/4561
- [ ] https://github.com/Azure/autorest.csharp/issues/4562
```

**Comment by m-nash** [comment]
@AlexanderSher can you update with which of these will exist.

**Comment by m-nash** [comment]
@jorgerangel-msft  can we split this up to 1 issue per class and put them in mid may iterations

**Comment by ArcturusZhang** [comment]
@AlexanderSher @m-nash I hope there could be a refactor around these types such as Alexander has done in his consolidation PR before we "migrate" them there because these "writer" helpers are really messy and not following the principal we would like to establish that the writers should just know nothing about what it is writing and everything should be prepared and built in the type provider (including models and clients).
I feel quite a lot pain while making the changes to update SCM around them.
