### ISSUE TITLE
[Epic] Remove generator dependency on `TypeFormatters`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#4372]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4373
- [ ] https://github.com/Azure/autorest.csharp/issues/4374
- [ ] https://github.com/Azure/autorest.csharp/issues/4375
- [ ] https://github.com/Azure/autorest.csharp/issues/4376
- [ ] https://github.com/Azure/autorest.csharp/issues/4377
```
