### ISSUE TITLE
Remove dependencies on Configuration.Configuration1ConvenienceClient after HLC and DPG models are consolidated

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#4410]
```[tasklist]
### Tasks
- [x] Add derived types list to the property description in DPG
- [ ] Consolidate property initializer generation between HLC and DPG
- [x] Generate FromOperationResponse and ToRequestContent in HLC
- [x] Resolve differences in HLC and DPG for ambiguous property names
- [ ] Provide a flag to add read/write properties to the public model constructor
- [ ] Consolidate default namespace choice between HLC and DPG
```
