### ISSUE TITLE
Multiple API-Version SDK

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#4455]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4456
- [ ] Mutiple api-version SDK
- [ ] Multiple api-version model generation: https://github.com/Azure/autorest.csharp/issues/2362
- [ ] Model resilency: https://github.com/Azure/autorest.csharp/issues/2354
- [ ] Multiple api-version operation generation
- [ ] Good document
```

**Comment by chunyu3** [comment]
We have implemented simple multiple-ApiVersion. Current We have no plan to support the comprehensive multiple-apiVersion sdk. close this issue first.
