### ISSUE TITLE
Additional properties C# user experience

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#4465]
# How to define `AdditionalProperties` in `TypeSpec`

## Phase 1

Make the additional properties with "verifiable primitive types" working correctly.

## Phase 2

Make the additional properties with the union of "verifiable primitive types" working correctly.

## Phase 3

Make the additional properties with models working correctly.

## Phase 4

Make the additional properties with collections working correctly.

## Phase 5

Make the complicated inheritance cases working correctly

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4128
- [ ] Phase 2: fully support additional properties with union types of verifiable primitive types
- [ ] Phase 3: fully support additional properties with models
- [ ] Phase 4: fully support additional properties with collections
- [ ] https://github.com/Azure/autorest.csharp/issues/4467
```

**Comment by lmazuel** [comment]
Closing, see C# doc here for design: https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/06types#models-with-additional-properties
