### ISSUE TITLE
Handle TypeSpec closed union

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4556]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4417
- [ ] https://github.com/Azure/autorest.csharp/issues/4419
- [ ] https://github.com/Azure/autorest.csharp/issues/4420
```
