### ISSUE TITLE
Add RestClient CreateRequest methods to RestClient class

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4561]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/typespec/issues/3680
- [ ] https://github.com/microsoft/typespec/issues/3681
- [ ] https://github.com/microsoft/typespec/issues/3679
```

**Comment by m-nash** [comment]
We may not migrate the helper as is since it uses direct code writer strings instead of expressions.

**Comment by JoshLove-msft** [comment]
This has been done.
