### ISSUE TITLE
Sample generation Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#4805]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4980
- [ ] https://github.com/Azure/autorest.csharp/issues/5006
- [ ] https://github.com/Azure/autorest.csharp/issues/4979
- [ ] https://github.com/Azure/autorest.csharp/issues/5015
- [ ] https://github.com/Azure/autorest.csharp/issues/4977
- [ ] https://github.com/Azure/autorest.csharp/issues/5002
- [ ] https://github.com/Azure/autorest.csharp/issues/5011
- [ ] https://github.com/Azure/autorest.csharp/issues/5033
- [ ] https://github.com/Azure/autorest.csharp/issues/5134
```

**Comment by chunyu3** [comment]
.NET SDK current generate Sample with mocked value.

**Comment by ArcturusZhang** [comment]
Current plan of adopting the examples from TCGC is:

1. Update the emitter so that the emitter could spit out the examples from TCGC.
2. Refine our code in DPG so that the sample generator made for DPG is able to write out those examples, as if they are the mock examples.
3. Refine our code in MPG so that the examples for mgmt could be written when the input is typespec.
4. Possible follow ups: use the responses, now the responses in examples are not used.

**Comment by ArcturusZhang** [comment]
The basic features for sample generation has been done - those left are improvements.
Closing this one and we will track those improvement in those individual issues
