### ISSUE TITLE
[Epic] Enable azure cadl-ranch test cases for every case

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#4843]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.csharp/issues/4844
- [ ] https://github.com/Azure/autorest.csharp/issues/5049
- [ ] https://github.com/Azure/autorest.csharp/issues/5050
- [ ] https://github.com/Azure/autorest.csharp/issues/5051
- [ ] https://github.com/Azure/autorest.csharp/issues/5052
- [ ] https://github.com/Azure/autorest.csharp/issues/5053
- [ ] https://github.com/Azure/autorest.csharp/issues/5054
- [ ] https://github.com/Azure/autorest.csharp/issues/5140
- [ ] https://github.com/Azure/autorest.csharp/issues/5141
- [ ] https://github.com/Azure/autorest.csharp/issues/5142
- [ ] https://github.com/Azure/autorest.csharp/issues/5143
- [ ] https://github.com/Azure/autorest.csharp/issues/5144
- [ ] https://github.com/Azure/autorest.csharp/issues/5145
- [ ] https://github.com/Azure/autorest.csharp/issues/5146
- [ ] https://github.com/Azure/autorest.csharp/issues/5147
- [ ] https://github.com/Azure/autorest.csharp/issues/5148
- [ ] https://github.com/Azure/autorest.csharp/issues/5149
```

**Comment by pshao25** [comment]
@melina5656 Please help work on the mgmt tests (tests under folder packages\cadl-ranch-specs\http\azure\resource-manager)
