### ISSUE TITLE
Remove test Models-TypeSpec 

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4845]
```[tasklist]
### Tasks
- [x] Move tests to cadl-ranch
- [x] Remove test\TestProjects\Models-TypeSpec, test\CadlRanchProjects.Tests\Models-TypeSpec.cs, test\CadlRanchMockApis\src\Models-TypeSpec.ts
- [x] Add tests from cadl-ranch
```
