### ISSUE TITLE
Remove test Spread-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4846]
```[tasklist]
### Tasks
- [x] Move tests to cadl-ranch
- [x] Remove test\TestProjects\Spread-TypeSpec, test\CadlRanchProjects.Tests\Models-Spread.cs, test\CadlRanchMockApis\src\Spread-TypeSpec.ts
- [x] Add tests from cadl-ranch
```
