### ISSUE TITLE
Remove test ApiVersion-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4847]
```[tasklist]
### Tasks
- [x] Move tests to cadl-ranch
- [x] Remove test\TestProjects\ApiVersion-TypeSpec
- [x] Add tests from cadl-ranch
```
