### ISSUE TITLE
Remove test Authoring-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4848]
```[tasklist]
### Tasks
- [ ] Move tests to cadl-ranch
- [ ] Remove test\TestProjects\Authoring-TypeSpec
- [ ] Add tests from cadl-ranch
```
