### ISSUE TITLE
Remove test ClientAndOperationGroup-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4849]
```[tasklist]
### Tasks
- [ ] Move tests to cadl-ranch
- [ ] Remove test\TestProjects\ClientAndOperationGroup-TypeSpec
- [ ] Add tests from cadl-ranch
```
