### ISSUE TITLE
Remove test LatestVersion-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4850]
```[tasklist]
### Tasks
- [x] Move tests to cadl-ranch
- [x] Remove test\TestProjects\LatestVersion-TypeSpec
- [x] Add tests from cadl-ranch
```
