### ISSUE TITLE
Remove test MediaTypes-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4851]
```[tasklist]
### Tasks
- [ ] Move tests to cadl-ranch
- [ ] Remove test\TestProjects\MediaTypes-TypeSpec
- [ ] Add tests from cadl-ranch
```
