### ISSUE TITLE
Remove test OldestVersion-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4853]
```[tasklist]
### Tasks
- [x] Move tests to cadl-ranch
- [x] Remove test\TestProjects\OldestVersion-TypeSpec
- [x] Add tests from cadl-ranch
```
