### ISSUE TITLE
Remove test Pagination-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4854]
```[tasklist]
### Tasks
- [x] Move tests to cadl-ranch
- [x] Remove test\TestProjects\Pagination-TypeSpec
- [x] Add tests from cadl-ranch
```
