### ISSUE TITLE
Remove test Parameters-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4855]
```[tasklist]
### Tasks
- [ ] Move tests to cadl-ranch
- [ ] Remove test\TestProjects\Parameters-TypeSpec
- [ ] Add tests from cadl-ranch
```
