### ISSUE TITLE
Remove test SpecificVersion-TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#4856]
```[tasklist]
### Tasks
- [ ] Move tests to cadl-ranch
- [ ] Remove test\TestProjects\SpecificVersion-TypeSpec
- [ ] Add tests from cadl-ranch
```
