### ISSUE TITLE
Encode int as string Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#4919]
```[tasklist]
### Tasks
- [x] Update emitter to consume new encode metadata
- [x] Change generator to support new encode metadata
- [ ] https://github.com/Azure/cadl-ranch/issues/634
- [ ] https://github.com/microsoft/typespec/issues/4109
- [ ] https://github.com/Azure/cadl-ranch/pull/656
- [ ] https://github.com/microsoft/typespec/pull/4186
```
